name: Deploy web app 🚀

on:
 push:
  branches:
  - main

env:
  AZURE_FUNCTION_NAME: RPG
  AZURE_FUNCTION_PACKAGE_PATH: "./"


jobs: 
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: dotnet restore ./FormsReminder.sln

    - name: Build Solution
      run: dotnet build ./FormsReminder.sln --configuration Release --no-restore

    - name: Publish Project
      run: dotnet publish ./FormsReminder.sln --configuration Release --no-build --output "${{ env.AZURE_FUNCTION_PACKAGE_PATH }}"